# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cfd826d88dd52cf856a73fdefc29fa52383f007e9b4024cf146216271901f81d1c1f49dfd9a8a6cbc5a552e1c0347b726fee5f4161cc4850188f841b01ee930

test:
  secret_key_base: 211a950520b47318d2fd36a0aba5121f2442a99cf79936b3592b1e2f4e1e11e18b04efe032d985a4a8dbd69db3a437a16d5c3f4c66a5ae447d0675de7a4aa8f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
